# TODO - we may want to merge it with fluxnova/templates/ingress.yaml (using if statement for the tls block)

apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: nginx
spec:
  controller: k8s.io/ingress-nginx
---
# ingress-tls.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fluxnova-tls
  namespace: fluxnova-ns
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-cloudflare"
    # nginx.ingress.kubernetes.io/auth-type: "basic"
    # nginx.ingress.kubernetes.io/auth-secret: "basic-auth"
    # nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - fluxnova"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - demo.fluxnova.finos.org
    secretName: fluxnova-tls
  rules:
  - host: demo.fluxnova.finos.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fluxnova
            port:
              number: 8080